# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'witAIdemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for witAIdemo
  # pod 'FirebaseMessaging'
  pod 'Firebase/Core'
  pod 'Google-Mobile-Ads-SDK'

  target 'witAIdemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'witAIdemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
